[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[redirects]]
  from = "/marketing/*"
  to = "/:splat"
  status = 200
  
[[plugins]]
package = "@netlify/plugin-nextjs"
